Switch to active_models_serializer.
Also got rid of the JSON gem since dumping a serializer was leading to
the exception: "NoMethodError: undefined method `fetch' for
#<JSON::Ext::Generator::State:0x9b55e24>".

Found some related discussion here[1] but did not get much out of it.
Now using the MultiJSON gem but not sure if it's the best solution.

[1]: https://github.com/intridea/multi_json/issues/86